export { default as Achievements } from "./Achievements";
export { default as Certifications } from "./Certifications";
export { default as Contact } from "./Contact";
export { default as Education } from "./Education";
export { default as Experiences } from "./Experiences";
export { default as Header } from "./Header";
export { default as Languages } from "./Languages";
export { default as Projects } from "./Projects";
export { default as Skills } from "./Skills";
